logging:
    level:
        '[org.springframework.web]': DEBUG
spring:
    datasource:
        url: jdbc:mariadb://localhost:3306/tour
        driver-class-name: org.mariadb.jdbc.Driver
        username: root
        password: tour